version: 0.2

phases:
  pre_build:
    commands:
      - echo maven build....
      - rm -rf target
      - mvn -Dmaven.skip.test package
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t angular .
      - docker tag angular:latest 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 090187438878.dkr.ecr.us-east-1.amazonaws.com/demo-pipeline-repo:latest
